#!/usr/bin/env python3
"""build_sitemap.py — sitemap.xml va news-sitemap.xml ni quradi.

Ilgari bu kod sitemap.yml ichida yozilgan edi va kuniga bir marta ishlardi.
Endi alohida fayl: news lenta ish oqimi ham har nashrdan keyin shuni
chaqiradi, ya'ni yangi xabar sitemap'ga bir necha soat emas, bir necha
soniyada tushadi.

Chiqish:
  sitemap.xml       — barcha sahifalar
  news-sitemap.xml  — Google News formati, faqat oxirgi 48 soatdagi xabarlar
"""

import json, urllib.request, datetime

req = urllib.request.Request(
    'https://flarestamina.com/ielts-hub/tests.json',
    headers={'User-Agent': 'Flarestamina-sitemap'})
tests = json.loads(urllib.request.urlopen(req, timeout=30).read())['tests']

# news posts live in the repo itself
posts = json.load(open('news/posts.json'))['posts']

# community pages generated by .github/scripts/build_community.py
try:
    ci = json.load(open('news/articles-index.json'))
    arts = ci.get('articles', {})
    authors = ci.get('authors', [])
except Exception:
    arts, authors = {}, []

# auto lenta pages generated by newsbot/src/build.mjs
try:
    lenta = json.load(open('news/lenta.json'))['posts']
except Exception:
    lenta = []

# A site-wide pass over the practice pages does not change tests.json, so
# lastmod would still claim May while the page had been rewritten that
# morning — and lastmod is the main hint Google has that a page is worth
# re-crawling. Bump REWRITE whenever a pass touches the test pages
# themselves (titles, H1s, markup); leave it alone for ordinary edits.
REWRITE = '2026-08-24'   # titles, H1s and answer-box labels across 89 pages

# stable lastmod (newest test date) so the file only changes when tests change
today = max([t.get('date') or '' for t in tests] + ['2026-07-03', REWRITE])
news_mod = max([p['date'] for p in posts] + ['2026-07-15'])
urls = [
    ('https://flarestamina.com/', today, 'weekly', '1.0'),
    ('https://flarestamina.com/ielts-hub/', today, 'daily', '0.9'),
    ('https://flarestamina.com/tests/', today, 'daily', '0.9'),
    ('https://flarestamina.com/ielts-listening-test/', today, 'daily', '0.9'),
    ('https://flarestamina.com/ielts-reading-test/', today, 'daily', '0.9'),
    ('https://flarestamina.com/uz/', today, 'weekly', '0.9'),
    ('https://flarestamina.com/uz/listening/', today, 'weekly', '0.9'),
    ('https://flarestamina.com/uz/reading/', today, 'weekly', '0.9'),
    ('https://flarestamina.com/uz/writing/', today, 'weekly', '0.8'),
    ('https://flarestamina.com/uz/speaking/', today, 'weekly', '0.8'),
    ('https://flarestamina.com/news/', news_mod, 'daily', '0.9'),
    ('https://flarestamina.com/news/lenta/',
     max([p['date'] for p in lenta] + [news_mod]), 'daily', '0.8'),
    ('https://flarestamina.com/founder/', '2026-07-15', 'monthly', '0.6'),
    ('https://flarestamina.com/writearticle/', '2026-07-15', 'monthly', '0.6'),
    ('https://flarestamina.com/convert/', '2026-07-16', 'monthly', '0.8'),
    ('https://flarestamina.com/deadlines/', '2026-07-17', 'weekly', '0.8'),
    ('https://flarestamina.com/plan/', '2026-07-18', 'monthly', '0.8'),
    ('https://flarestamina.com/speaking-topics/', '2026-07-17', 'monthly', '0.8'),
    ('https://flarestamina.com/writing/', REWRITE, 'monthly', '0.9'),
    ('https://flarestamina.com/teachers/', today, 'monthly', '0.8'),
    ('https://flarestamina.com/privacy/', today, 'yearly', '0.3'),
    ('https://flarestamina.com/wedding/', '2026-07-16', 'monthly', '0.7'),
]
seen = {u[0] for u in urls}
for p in posts:
    u = f"https://flarestamina.com/news/{p['slug']}/"
    if u in seen:
        continue
    seen.add(u)
    urls.append((u, p['date'], 'monthly', '0.8'))

# one indexable page per auto lenta post
for p in lenta:
    u = f"https://flarestamina.com/news/x/{p['slug']}/"
    if u in seen:
        continue
    seen.add(u)
    urls.append((u, p['date'], 'monthly', '0.6'))

# one indexable page per community article + per author
for meta in arts.values():
    u = f"https://flarestamina.com/news/a/{meta['slug']}/"
    if u in seen:
        continue
    seen.add(u)
    urls.append((u, meta.get('date') or news_mod, 'monthly', '0.7'))
for a in authors:
    u = f"https://flarestamina.com/news/t/{a}/"
    if u in seen:
        continue
    seen.add(u)
    urls.append((u, news_mod, 'weekly', '0.6'))
for t in tests:
    u = (t.get('url') or '').strip()
    if not u or u in seen:
        continue
    if not u.startswith('https://flarestamina.com'):
        continue  # skip external tools (e.g. pierics.com) — not our sitemap
    seen.add(u)
    # the page was rewritten on REWRITE even though its test date is older
    urls.append((u, max(t.get('date') or '', REWRITE), 'monthly', '0.7'))

out = ['<?xml version="1.0" encoding="UTF-8"?>',
       '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
for loc, mod, freq, pri in urls:
    out.append(f'  <url><loc>{loc}</loc><lastmod>{mod}</lastmod>'
               f'<changefreq>{freq}</changefreq><priority>{pri}</priority></url>')
out.append('</urlset>')
open('sitemap.xml', 'w').write('\n'.join(out) + '\n')
print('URLs:', len(urls))

# ── Google News sitemap ────────────────────────────────────────────────────
#
# Google News alohida format talab qiladi va faqat OXIRGI 48 SOATdagi
# maqolalarni qabul qiladi — eskilarini qo'shish xato hisoblanadi.
# Shuning uchun bu fayl har nashrdan keyin qayta quriladi va ko'pincha
# bo'sh bo'ladi. Bo'sh news sitemap normal holat.

def esc(s):
    return (s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
             .replace('"', '&quot;').replace("'", '&apos;'))


now = datetime.datetime.now(datetime.timezone.utc)
recent = []

# lenta xabarlari: sana kunlik aniqlikda, shuning uchun 2 kunlik oyna
for p in lenta:
    try:
        d = datetime.datetime.strptime(p['date'], '%Y-%m-%d').replace(tzinfo=datetime.timezone.utc)
    except Exception:
        continue
    if (now - d).days > 2:
        continue
    recent.append((f"https://flarestamina.com/news/x/{p['slug']}/", p['title'], p['date']))

# qo'lda yozilgan postlar ham yangi bo'lsa kiradi
for p in posts:
    try:
        d = datetime.datetime.strptime(p['date'], '%Y-%m-%d').replace(tzinfo=datetime.timezone.utc)
    except Exception:
        continue
    if (now - d).days > 2:
        continue
    recent.append((f"https://flarestamina.com/news/{p['slug']}/", p['title'], p['date']))

nout = ['<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
        '        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">']
for loc, title, date in recent:
    nout.append('  <url>')
    nout.append(f'    <loc>{loc}</loc>')
    nout.append('    <news:news>')
    nout.append('      <news:publication>')
    nout.append('        <news:name>Flarestamina</news:name>')
    nout.append('        <news:language>uz</news:language>')
    nout.append('      </news:publication>')
    nout.append(f'      <news:publication_date>{date}</news:publication_date>')
    nout.append(f'      <news:title>{esc(title)}</news:title>')
    nout.append('    </news:news>')
    nout.append('  </url>')
nout.append('</urlset>')
open('news-sitemap.xml', 'w').write('\n'.join(nout) + '\n')
print('News sitemap:', len(recent))
