#!/usr/bin/env python3
"""Generate logo-dots.json for ?logo=dots — build time only, never at runtime.

The mark is a four-pointed star, not a triangle, so a Cartesian grid turns it
into a plus sign. Sampling is polar instead: one line of dots per arm, walked
outward with the step taken from the arm's own half-width, so the spacing
tightens toward the tip because the arm narrows; plus concentric rings inside
the square centre mass.

Coordinates are the committed asset's own 32x32 space, centre at (16, 16).
"""
import json, math

C, ARM, W, WAT = 16.0, 14.6, 1.85, 2.45   # centre, arm length, half-waist
AXES = [(0, -1), (1, 0), (0, 1), (-1, 0)]  # top, right, bottom, left

def half_width(a):
    """Half-width of an arm at axial distance a from the centre."""
    return W * (ARM - a) / (ARM - WAT)

dots = []

# --- four arms -------------------------------------------------------------
for ax, ay in AXES:
    a = 2.9
    while a < 14.45:
        r = max(0.13, min(0.72, 0.9 * half_width(a)))
        dots.append((C + ax * a, C + ay * a, r))
        a += 2 * r * 1.10 + 0.05

# --- centre mass: a dot and two rings, inside the square of half-side 1.85 --
dots.append((C, C, 0.42))
for radius, count, dr, phase in ((0.95, 6, 0.34, 0.0), (1.52, 10, 0.30, math.pi / 10)):
    for i in range(count):
        t = phase + 2 * math.pi * i / count
        dots.append((C + radius * math.cos(t), C + radius * math.sin(t), dr))

out = {
    "note": "generated by gen-dots.py; positions are in the mark's 32x32 space",
    "viewBox": "-13 -13 58 58",
    "centre": [C, C],
    "count": len(dots),
    "dots": [[round(x, 3), round(y, 3), round(r, 3)] for x, y, r in dots],
}
with open(__file__.rsplit('/', 1)[0] + '/logo-dots.json', 'w') as f:
    json.dump(out, f, separators=(',', ':'))
print('dots:', len(dots), '| per arm:', (len(dots) - 17) // 4)
